import pandas as pd
df=pd.read_csv("Weather_data.csv")
print("-----Original Data is------")
print(df)
print("-----Transformed Data is------")
df.columns=df.columns.str.strip()
df1=df.pivot(index='date',columns='city')
print(df1)
print("If I want humidity in my output,for that I have to add third argument values")
df.columns=df.columns.str.strip()
df2=df.pivot(index='date',columns='city',values='humidity')
print(df2)
print("----Use of pivot table----")
print("-----Sum-------")
df=pd.read_csv("Weather_data_t.csv")
df.columns=df.columns.str.strip()
df1=df.pivot_table(index='city',columns='date',aggfunc='sum')
print("Sum",df1)
df=pd.read_csv("Weather_data_t.csv")
df.columns=df.columns.str.strip()
df1=df.pivot_table(index='city',columns='date')
print("-----Average-------")
print(df1)
